apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    example:
      owner: faiza293
      repository: ArgoCD-GKE # eg. eg. frontend, backend, myapi
      webhook:
        url: https://34.70.215.99/api/webhook
        endpoint: /my-event
        port: "12000"
        method: POST
      events:
        - "*"
      webhookSecret:
        name: webhook-token
        key: my-token
      insecure: false
      active: true
      contentType: "json"