apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app   #name of the application
spec:
  destination:
    server: 'https://34.171.22.205'
    #name: 'uat-gke'  #GKE cluster name where the application will get deployed
    namespace: uat-namespace
  source:
    path: argoapps #deployment yaml file path to be referred in the git 
    repoURL: 'https://github.com/faiza293/ArgoCD-GKE.git'  #git repo url where deployment file is present
    targetRevision: main #git branch
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: argocd-project  #argocd project 
  syncPolicy:
    automated:  # this will automatically sync the deployment file
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true #If the namespace is not present, this will create a specified namespace in the cluster
      - PruneLast=true
      - PrunePropagationPolicy=foreground