apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-staging
  labels:
    app: nginx
    environment: staging
spec:
  replicas: 2  # Staging might have fewer replicas
  selector:
    matchLabels:
      app: nginx
      environment: staging
  template:
    metadata:
      labels:
        app: nginx
        environment: staging
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-staging
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
    environment: staging
